version: '3.8'

services:
  api:
    image: node:18-alpine
    environment:
      - DATABASE_URL= ${DATABASE_URL}
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '8080:8080'
    command: npx nodemon -L ./src/app.ts
    networks:
      - mycloud
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - ${DOCKER_VOLUME_PATH}/postgres_data:/var/lib/postgresql/data
    networks:
      - mycloud

networks:
  mycloud:
    driver: bridge
